config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homepage#index'
  resources :homepage, only: [:index]

  namespace :api do
    resources :catches, only: [:index] do
      collection do
        get 'personal'
      end
    end
    resources :fish_types, only: [:show]
  end

  resources :catches do
    collection do
      get 'recent'
    end
    collection do
      get 'personal'
    end
  end

  resources :lures do
    collection do
      get 'hot'
    end
  end

  resources :fish_types do
    collection do
      get 'hot'
    end
  end
end

app/models/catch.rb
class Catch < ActiveRecord::Base
  mount_uploader :catch_photo, CatchPhotoUploader

  belongs_to :user
  belongs_to :lure
  belongs_to :fish_type

  validates :user_id, presence: true
  validates :lure_id, presence: true
  validates :fish_type_id, presence: true
  validates :latitude, presence: true
  validates :latitude, numericality: { greater_than_or_equal_to: -90, less_than_or_equal_to: 90 }
  validates :longitude, presence: true
  validates :longitude, numericality: { greater_than_or_equal_to: -180, less_than_or_equal_to: 180 }
  validates :caught_at, presence: true
end

app/controllers/api/catches_controller.rb
class Api::CatchesController < ApiController
  def index
    catches = Catch.all
    render json: { catches: catches }, status: :ok
  end
  def personal
    catches = Catch.where("user": current_user)
    render json: { catches: catches }, status: :ok
  end
end

app/controllers/catches_controller.rb
class CatchesController < ApplicationController
  before_action :authenticate_user!, except: [:recent, :index, :show]

  def recent
    if params["l"].present?
      @lure = Lure.where("name ILIKE ?", "%#{params[:l]}%")
      if @lure.present?
        @search = params["l"]
        @catches = Catch.where("lure": @lure)
      else
        @search = params["l"]
        render :recent
      end
    elsif params["f"].present?
      @fish = FishType.where("name ILIKE ?", "%#{params[:f]}%")
      if @fish.present?
        @search = params["f"]
        @catches = Catch.where("fish_type": @fish)
      else
        @search = params["f"]
        render :recent
      end
    else
      @catches = Catch.order(caught_at: :desc)
    end
  end

  def personal
    @catches = Catch.where("user": current_user)
  end

  def index
    @catches = Catch.all
  end

  def show
    @catch = Catch.find(params[:id])
  end

  def new
    @catch = Catch.new
  end

  def create
    @catch = Catch.new(catch_params)
    @catch.user = current_user
    if params[:catch][:fish_type].present? && params[:catch][:lure].present?
      @catch.fish_type = FishType.find(params[:catch][:fish_type])
      @catch.lure = Lure.find(params[:catch][:lure])
    end

    if @catch.save
      flash[:notice] = "Your catch has been recorded!"
      redirect_to catch_path(@catch)
    else
      flash[:errors] = @catch.errors.full_messages.join(", ")
      render :new
    end
  end

  def edit
    @catch = Catch.find(params[:id])
  end

  def update
    @catch = Catch.find(params[:id])
    if @catch.update_attributes(catch_params)
      flash[:notice] = "Your catch was updated successfully"
      redirect_to catch_path(@catch)
    else
      flash[:errors] = @catch.errors.full_messages.join(",")
      render :edit
    end
  end

  def destroy
    @catch = Catch.find(params[:id])
    @catch.destroy
    flash[:notice] = "Catch deleted successfully"
    redirect_to catches_path
  end

  private

  def catch_params
    params.require(:catch).permit(
      :caught_at,
      :catch_photo,
      :latitude,
      :longitude
    )
  end
end

app/views/catches/edit.html.erb
<div class="callout">
  <h2 class="header-title">Update your Catch</h2>
  <div>
    <%= form_for @catch do |f| %>
  <div class="row">
    <div class="large-6 small-12 columns">
      <div class="small-6 columns">
        <%= f.label :lure, "Lure" %>
        <%= f.select(:lure, Lure.all.collect {|lure| [ lure.name, lure.id ] }, :prompt => "Select a Lure") %>
        <%= link_to "Add a Lure", new_lure_path %>

      </div>
      <div class="small-6 columns">
        <%= f.label :fish_type, "Fish" %>
        <%= f.select(:fish_type, FishType.all.collect {|fish| [ fish.name, fish.id ] }, :prompt => "Select a Fish") %>
        <%= link_to "Add a Fish", new_fish_type_path %>
      </div>
      <div class="row">
        <div class="small-6 columns">
          <%= f.label :latitude, "Latitude" %>
          <%= f.text_field :latitude %>
        </div>
        <div class="small-6 columns">
          <%= f.label :longitude, "Longitude" %>
          <%= f.text_field :longitude %>
        </div>
      </div>
      <%= f.label :caught_at, "Caught on:" %>
      <%= f.date_field :caught_at %>

      <%= f.label :catch_photo, "Add a picture of your catch!" %>
      <%= f.file_field :catch_photo %>

      <%= f.submit "Update Catch", id: "add-catch"%>
      <% end %>
    </div>
    <div class="large-6 small-12 columns" id="map-holder">
      <a href='#' id='locate-me' class='button'>Locate Me</a>
      <div id='map'></div>
    </div>
  </div>
</div>

<script>
  $(document).ready(function () {
    var catchLat = document.getElementById("catch_latitude").value;
    var catchLng = document.getElementById("catch_longitude").value;
    drawEditCatchMap(catchLat, catchLng);
  });
</script>

app/views/catches/index.html.erb
<div class="callout">
<h2 class="header-title">All Catches</h2>
  <div class="row">
    <div class="catch large-6 small-12 columns">
      <% @catches.each do |c| %>
        <ul>
          <li><%= link_to c.caught_at.strftime("Caught on %m/%d/%Y"), catch_path(c) %></li>
          <ul>
            <li><%= link_to c.lure.name, lure_path(c.lure) %></li>
            <li><%= link_to c.fish_type.name, fish_type_path(c.fish_type) %></li>
          </ul>
        </ul>
        <br>
        <% end %>
      </div>
    <div class="large-6 small-12 small-centered columns" id="map-holder">
      <a href='#' id='locate-me' class='button'>Locate Me</a>
      <div id='map' class="large-12 small-12 small-centered columns"></div>

      <script type="text/javascript">
        drawIndexCatchMap();
      </script>
    </div>
  </div>
</div>

app/views/catches/new.html.erb
<div class="callout">
  <h2 class="header-title">Report what you caught here!</h2>

  <div class="row">
    <div class="large-6 small-12 columns">

    <%= form_for @catch do |f| %>
      <div class="row">
        <div class="small-6 columns">
          <%= f.label :lure, "Lure" %>
          <%= f.select(:lure, Lure.all.collect {|lure| [ lure.name, lure.id ] }, :prompt => "Select a Lure") %>
          <%= link_to "Add a Lure", new_lure_path %>

        </div>
        <div class="small-6 columns">
          <%= f.label :fish_type, "Fish" %>
          <%= f.select(:fish_type, FishType.all.collect {|fish| [ fish.name, fish.id ] }, :prompt => "Select a Fish") %>
          <%= link_to "Add a Fish", new_fish_type_path %>
        </div>
        <div class="row">
          <div class="small-6 columns">
            <%= f.label :latitude, "Latitude" %>
            <%= f.text_field :latitude %>
          </div>
          <div class="small-6 columns">
            <%= f.label :longitude, "Longitude" %>
            <%= f.text_field :longitude %>
          </div>
        </div>
        <div class="row">
          <div class="small-6 small-centered column">
            <%= f.label :caught_at, "Caught on:" %>
            <%= f.date_field :caught_at %>

            <%= f.label :catch_photo, "Add a picture of your catch!" %>
            <%= f.file_field :catch_photo %>

            <%= f.submit "Report it!", class: "button" %>
            <% end %>
          </div>
        </div>
      </div>
    </div>
    <div class="large-6 small-12 small-centered columns" id="map-holder">
      <a href='#' id='locate-me' class='button'>Locate Me</a>
      <div id='map'></div>
    </div>
  </div>
</div>

<script>
  drawNewCatchMap();
</script>

app/views/catches/personal.html.erb
<div class="callout">
  <h2 class="header-title">Your Catches</h2>
  <div class="row">
    <div class="catch large-6 small-12 columns">
      <% if @catches.length == 0 %>
      <h4>You haven't reported any Catches yet!</h4>
      <% else %>
        <% @catches.each do |c| %>
          <ul>
            <li><%= link_to c.caught_at.strftime("Caught on %m/%d/%Y"), catch_path(c) %></li>
            <ul>
              <li><%= link_to c.lure.name, lure_path(c.lure) %></li>
              <li><%= link_to c.fish_type.name, fish_type_path(c.fish_type) %></li>
            </ul>
          </ul>
          <br>
          <% end %>
        <% end %>
      </div>
    <div class="large-6 small-12 small-centered columns" id="map-holder">
      <a href='#' id='locate-me' class='button'>Locate Me</a>
      <div id='map' class="large-12 small-12 small-centered columns"></div>

      <script type="text/javascript">
        drawPersonalCatchMap();
      </script>
    </div>
  </div>
</div>

app/views/catches/recent.html.erb
<div class="callout">
  <h2 class="header-title">Most Recent Catches</h2>
  <div class="row">
    <div class="catch large-6 small-12 columns">
      <% if @catches.nil? %>
      <h5>Sorry, there are no reported catches matching your search request: <%= @search %></h5>
      <% else %>
      <h4>These catches matched your search request: <%= @search %> </h4>
        <% @catches.each do |c| %>
          <ul>
            <li><%= link_to c.caught_at.strftime("Caught on %m/%d/%Y"), catch_path(c) %></li>
            <ul>
              <li><%= link_to c.lure.name, lure_path(c.lure) %></li>
              <li><%= link_to c.fish_type.name, fish_type_path(c.fish_type) %></li>
            </ul>
          </ul>
          <br>
          <% end %>
        <% end %>
      </div>
    <div class="large-6 small-12 small-centered columns" id="map-holder">
      <a href='#' id='locate-me' class='button'>Locate Me</a>
      <div id='map' class="large-12 small-12 small-centered columns"></div>

      <script type="text/javascript">
        drawIndexCatchMap();
      </script>
    </div>
  </div>
</div>

app/views/catches/show.html.erb
<div class="callout">
<h2 class="header-title">Catch #<%= @catch.id %></h2>
  <div class="row">
    <div class="catch large-6 small-12 columns">
      <div class="user-info">
        <ul>
          <li>Caught by: <%= @catch.user.username %></li>
          <li><%= @catch.caught_at.strftime("Caught on %m/%d/%Y") %></li>
          <% if !current_user.nil? %>
            <% if current_user.id == @catch.user.id %>
              <li>
                <%= link_to "Update your Catch", edit_catch_path(@catch) %>
              </li>
              <li>
                <%= link_to "Delete your Catch", catch_path(@catch), data: { :confirm => "Are you sure?" }, method: :delete %>
              </li>
            <% end %>
          <% end %>
        </ul>
      </div>
      <div class="catch-info">
        <ul>
          <li>Fish caught: <%= @catch.fish_type.name %></li>
        </ul>
        <% if !@catch.catch_photo.file.nil? %>
        <div class="catch-photo">
          <%= image_tag @catch.catch_photo %>
        </div>
        <% end %>
        <ul>
          <li>Lure used: <%= @catch.lure.name %></li>
          <ul>
            <li>Manufacturer: <%= @catch.lure.manufacturer %></li>
            <li>Category: <%= @catch.lure.category %></li>
          </ul>
        </ul>
        <ul>
          <li>Latitude:</li>
          <li id="latitude"><%= @catch.latitude %></li>
          <li>Longitude:</li>
          <li id="longitude"><%= @catch.longitude %></li>
        </ul>
      </div>

    </div>

    <div class="large-6 small-12 small-centered columns" id="map-holder">
      <div id="map"></div>
      <script>
      $(document).ready(function () {
        var catchLat = document.getElementById("latitude").innerHTML;
        var catchLng = document.getElementById("longitude").innerHTML;
        drawShowCatchMap(catchLat, catchLng);
      });
      </script>

    </div>
  </div>
</div>