config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  root 'homepage#index'
  resources :homepage, only: [:index]

  namespace :api do
    resources :catches, only: [:index] do
      collection do
        get 'personal'
      end
    end
    resources :fish_types, only: [:show]
  end

  resources :catches do
    collection do
      get 'recent'
    end
    collection do
      get 'personal'
    end
  end

  resources :lures do
    collection do
      get 'hot'
    end
  end

  resources :fish_types do
    collection do
      get 'hot'
    end
  end
end

app/views/layouts/_buttons.html.erb
<div id="button-group">

<button class="button" type="button" data-toggle="catches-dropdown">Recent Catches</button>
<div class="dropdown-pane" id="catches-dropdown" data-dropdown data-auto-focus="true">
  <div class="row">
    Narrow your search
  </div>
  <br>
  <div class="row">
    <%= form_tag(recent_catches_path, method: "get") do %>
    <div class="small-6 columns">
      <label>Fish
        <%= text_field_tag(:f) %>
      </label>
    </div>
    <div class="small-6 columns">
      <label>Lure
        <%= text_field_tag(:l) %>
      </label>
    </div>
    <br>
    <div class="row">
      <div class="small-6 columns">
        <%= link_to "All Recent Catches", catches_path %>
      </div>
      <div class="small-6 columns">
        <%= submit_tag("Search Recent Catches", class: 'button') %>
      </div>
      <% end %>
    </div>
  </div>
</div>
  <button class="button" type="button" data-toggle="lures-dropdown">Lures</button>
  <div class="dropdown-pane" id="lures-dropdown" data-dropdown data-auto-focus="true">
    <div class="row">
      Narrow your search
    </div>
    <br>
    <div class="row">
      <%= form_tag(hot_lures_path, method: "get") do %>
      <div class="small-6 columns">
        <label>Fish
          <%= text_field_tag(:f) %>
        </label>
      </div>
      <div class="small-6 columns">
        <%= link_to "All Lures", lures_path %>
        <br>
        <%= submit_tag("Search Hot Lures", {:class => 'button'}) %>
      </div>
      <% end %>
    </div>
  </div>
<button class="button" type="button" data-toggle="fish-type-dropdown">Fish</button>
<div class="dropdown-pane" id="fish-type-dropdown" data-dropdown data-auto-focus="true">
  <div class="row">
    Narrow your search
  </div>
  <br>
  <div class="row">
    <%= form_tag(hot_fish_types_path, method: "get") do %>
    <div class="small-6 columns">
      <label>Lure
        <%= text_field_tag(:l) %>
      </label>
    </div>
    <div class="small-6 columns">
      <%= link_to "All Fish", fish_types_path %>
      <br>
      <%= submit_tag("Search Fish", {:class => 'button'}) %>
    </div>
    <% end %>
  </div>
</div>
</div>

app/views/layouts/_header.html.erb
<div class="top-bar" id="navigation">
  <div class="top-bar-left">
    <ul class="menu">
      <li>
        <div id="trout-image">
          <%= image_tag("rising-trout.png") %>
        </div>
      </li>
      <li class="menu-text" id="title-nav">
        <%= link_to "FishAllure", root_path %>
      </li>
      <li class="nav-buttons"><%= link_to "Report your Catch", new_catch_path %></li>
    </ul>
  </div>
  <div class="top-bar-right">
    <ul class="dropdown-menu" data-dropdown-menu>
      <% if user_signed_in? %>
      <li class="nav-buttons" id="profile-nav"><%= link_to current_user.username, edit_user_registration_path %>
        <ul class="menu">
          <li class="nav-buttons"><%= link_to "Sign Out", destroy_user_session_path, :method => :delete %></li>
          <li class="nav-buttons"><%= link_to "My Catches", personal_catches_path %></li>
        </ul>
      </li>
      <% else %>
        <li class="nav-buttons"><%= link_to "Sign In", new_user_session_path %></li>
      <% end %>
    </ul>
  </div>
</div>
<br>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title><%= content_for?(:title) ? yield(:title) : "FishAllure" %></title>
    <link href="https://fonts.googleapis.com/css?family=IM+Fell+English+SC" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Rock+Salt" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Cinzel+Decorative:900" rel="stylesheet">
    <link href='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.css' rel='stylesheet' />
    <script src='https://api.mapbox.com/mapbox.js/v2.4.0/mapbox.js'></script>
    <%= stylesheet_link_tag    "application" %>
    <%= javascript_include_tag "application", 'data-turbolinks-track' => true %>
    <%= csrf_meta_tags %>
  </head>

  <body>
    <%= render partial: '/layouts/header' %>
    <%= render partial: '/layouts/buttons' %>

      <% flash.each do |key, value| %>
      <div class="callout">
        <div class="alert alert-<%= key %>"><%= value %></div>
      </div>
      <% end %>
      <div class="row">
        <div class="columns">
          <%= yield %>
        </div>
      </div>

  </body>
</html>